from dataclasses import dataclass, field
from typing import Any
from uuid import uuid4

from .models import AgentRequest


@dataclass(slots=True)
class Layer1Context:
    """Holds metadata generated by Layer 1 analysis stages."""
    intent: str | None = None
    task_category: str | None = None
    confidence_score: float = 0.0
    capabilities: list[str] = field(default_factory=list)
    allowed_tools: list[str] = field(default_factory=list)
    validation_result: dict[str, Any] = field(default_factory=dict)
    risk_level: str = "UNKNOWN"
    risk_score: float = 0.0
    risk_factors: list[str] = field(default_factory=list)
    execution_recommendation: str | None = None


@dataclass(slots=True)
class ExecutionContext:
    """Represents the current execution context."""
    request: AgentRequest
    execution_id: str = field(default_factory=lambda: str(uuid4()))
    correlation_id: str = field(default_factory=lambda: str(uuid4()))
    started_at: float = field(default_factory=lambda: 0.0)
    sdk_version: str = "1.0.0"
    runtime_version: str = "1.0.0"
    project_name: str = "aegis-default"
    environment: str = "development"
    layer1: Layer1Context = field(default_factory=Layer1Context)
    state: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)