from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class AgentRequest:
    """Represents a request sent to the runtime."""

    prompt: str
    stream: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)


# ==============================================================================
# Layer 4 Models (Memory & Knowledge)
# ==============================================================================

@dataclass(slots=True)
class MemorySource:
    """
    Metadata defining a memory partition, knowledge base, or state backend.
    """
    name: str
    provider_name: str
    namespace: str
    scope: str  # e.g., 'session', 'user', 'global'
    enabled: bool = True
    persistent: bool = False
    semantic: bool = False
    embedding_model: str | None = None
    ttl: int | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

@dataclass(slots=True)
class MemoryMetadata:
    """Telemetry data generated by every memory operation (read/write/search/delete)."""
    memory_id: str
    provider_name: str
    namespace: str
    operation: str
    latency_ms: float
    status: str
    timestamp: float


@dataclass(slots=True)
class ToolCall:
    """Represents a single tool invocation."""

    name: str
    arguments: dict[str, Any] = field(default_factory=dict)
    result: Any | None = None
    success: bool = False


@dataclass(slots=True)
class ToolMetadata:
    """Strongly typed metadata for a registered executable tool."""
    name: str
    description: str
    category: str = "general"
    version: str = "1.0.0"
    provider: str = "local"
    permissions: list[str] = field(default_factory=list)
    timeout_seconds: float = 30.0
    retry_policy: str = "exponential"  # 'none', 'fixed', 'linear', 'exponential'
    supports_streaming: bool = False
    enabled: bool = True
    tags: list[str] = field(default_factory=list)


@dataclass(slots=True)
class RegisteredTool:
    """Combines metadata with the actual executable implementation."""
    metadata: ToolMetadata
    executable: Any  # The actual callable or BaseTool implementation



@dataclass(slots=True)
class ProviderMetadata:
    """Strongly typed metadata for a registered provider."""
    name: str
    description: str
    capabilities: list[str] = field(default_factory=list)  # e.g. ["chat", "embeddings"]
    timeout_seconds: float = 60.0
    retry_policy: str = "exponential"
    supports_streaming: bool = True
    enabled: bool = True
    tags: list[str] = field(default_factory=list)


@dataclass(slots=True)
class RegisteredProvider:
    """Combines metadata with the actual provider implementation."""
    metadata: ProviderMetadata
    executable: Any  # The LLMProvider implementation


@dataclass(slots=True)
class ExecutionPlan:
    """Represents the execution plan generated by the planner."""

    reasoning: str
    steps: list[str] = field(default_factory=list)


@dataclass(slots=True)
class ExecutionResult:
    """Represents the final execution result."""

    output: str
    tool_calls: list[ToolCall] = field(default_factory=list)
    tokens_used: int = 0
    execution_time: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class ProposedAction:
    """Represents an action proposed by the Planner, before Layer 2 approval."""
    tool_name: str
    arguments: dict[str, Any]
    reasoning: str | None = None


@dataclass(slots=True)
class GovernanceResult:
    """Represents the outcome of Layer 2 Execution Governance."""
    approved: bool
    approved_action: ProposedAction | None = None
    constraints: dict[str, Any] = field(default_factory=dict)
    failed_validator: str | None = None
    failure_reason: str | None = None
    audit_event: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class ExecutionMetadata:
    """Represents audit information from Runtime Execution."""
    tool_name: str
    success: bool
    execution_time_ms: float
    retries_attempted: int
    timeout_occurred: bool
    exception_details: str | None = None
    
    # Phase 3.9: Extended Telemetry and Tracking Metadata
    request_id: str | None = None
    execution_id: str | None = None
    action_id: str | None = None
    provider: str | None = None
    status: str = "pending"
    start_time: float = 0.0
    end_time: float = 0.0


@dataclass(slots=True)
class NormalizedExecutionResult:
    """Represents the standardized result returned to the Planner."""
    tool_name: str
    success: bool
    output: str
    metadata: ExecutionMetadata | None = None


@dataclass(slots=True)
class BehaviorState:
    """Tracks execution behavior across multiple tool calls to prevent loops/drifts."""
    call_counts: dict[str, int] = field(default_factory=dict)
    consecutive_failures: int = 0
    total_execution_time_ms: float = 0.0
    history: list[ExecutionMetadata] = field(default_factory=list)